services:
  backend:
    build: ./backend
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    pid: host
    privileged: true
    group_add:
      - "984"
    networks:
      - server-monitor-network

  frontend:
    build: ./frontend
    ports:
      - "3011:80"
    depends_on:
      - backend
    networks:
      - server-monitor-network

networks:
  server-monitor-network:
    driver: bridge
